/*********************************************************************************
Program:    Test Class for AssignmentWizardController_1 to _10

**********************************************************************************/ 
@isTest(SeeAllData=True)
private class AssignmentWizard_Dummy {
    
  private static testMethod void testAssignmentWizardController1_10() {
       AssignmentWizardController_1 aswCont1 = new AssignmentWizardController_1();
       AssignmentWizardController_2 aswCont2 = new AssignmentWizardController_2();
       AssignmentWizardController_3 aswCont3 = new AssignmentWizardController_3();
       AssignmentWizardController_4 aswCont4 = new AssignmentWizardController_4();
       AssignmentWizardController_5 aswCont5 = new AssignmentWizardController_5();
       AssignmentWizardController_6 aswCont6 = new AssignmentWizardController_6();
       AssignmentWizardController_7 aswCont7 = new AssignmentWizardController_7();
       AssignmentWizardController_8 aswCont8 = new AssignmentWizardController_8();
       AssignmentWizardController_9 aswCont9 = new AssignmentWizardController_9();
       AssignmentWizardController_10 aswCont10 = new AssignmentWizardController_10();
       
       
  }


  }