@isTest(SeeAllData=True)
public class ContactAllTest {
    /*public static testMethod void runAllTests() {
        Account newAccount = new Account();
        newAccount.Name = 'SFDC';
        newAccount.Type = 'Other';
        newAccount.BillingStreet = 'Test Address';
        newAccount.BillingCity = 'Test City';
        newAccount.BillingCountry = 'Test Country';
        insert newAccount;         
    
        Contact newCnt1 = new Contact();
        newCnt1.FirstName = 'SFDC';
        newCnt1.LastName = 'Salesforce';
        newCnt1.email = 'xyz@gmail.com';
        newCnt1.AccountId = newAccount.Id;
        insert newCnt1;    

        Contact newCnt2 = new Contact();
        newCnt2.FirstName = 'SFDC';
        newCnt2.LastName = 'Salesforce';
        newCnt2.AccountId = newAccount.Id;
        newCnt2.email = 'xyz@gmail.com';        
        try {
            insert newCnt2;
        }
        catch(Exception e) {
        }
    }*/
}