public class SpringCMShareLink {
	public String Url {get;set;}
	public String ExpirationDate {get;set;}
	public Boolean AllowNativeDownload {get;set;}
	public Boolean AllowPdfDownload {get;set;}
	public String PreviewBehavior {get;set;}
	public String CreatedBy {get;set;}
	public String UpdatedBy {get;set;}
	public String CreatedDate {get;set;}
	public String UpdatedDate {get;set;}
	public SpringCMFolder Folder {get;set;}
	public SpringCMDocument Document {get;set;}
	public String Href {get;set;}
}