/********************************************************************
Purpose:To validate the functionality of fallowing classes
1.MainController
*********************************************************************/
@isTest
private class TestMainController 
{
      //Commented the code as we are achieving the same in 'MainController_Test' class
      /*static testMethod void validateTestMainController() 
      {
              PageReference pageRef = new PageReference('/apex/supportPlatformsapps');
              Test.setCurrentPage(pageRef);
              MainController testMC=new MainController();
              
              testMC.searchText = 'abc';
              testMC.globalSearchRedirectTo();
              testMC.getCachedCase();
              testMC.getCachedCaseNumber();
              testMC.pam_initSingleton();
              testMC.csm_initSingleton();
              testMC.qpm_initSingleton();
              testMC.qpm_initSupportLandingSingleton();
              testMC.rcm_initSingleton();
              testMC.arm_initSingleton();
              testMC.gsm_initSingleton();
              testMC.cvm_initSingleton();
              testMC.nfm_initSingleton();
              testMC.pdm_initSingleton();
              TrainingPagesModeler tpm = new TrainingPagesModeler();
              testMC.pdm_initSingleton();
               testMC.tpm_initSingleton();
               
              
              
              
      }*/
}